services:
  testrunner:
    image: $DEV_IMAGE_TAG
    environment:
      WORK_DIR: $PWD
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
    volumes:
      - .:$PWD
    hostname: progressor
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: $PWD

  postgres:
    image: postgres:15-bookworm
    command: -c 'wal_level=logical'
    environment:
      POSTGRES_DB: "progressor_db"
      POSTGRES_USER: "progressor"
      POSTGRES_PASSWORD: "progressor"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U progressor -d progressor_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
